tarushi_component
SachinMakwana/GECP_Admin_Angular pull request #23
Opened 2020-09-29 05:43 UTC by TarushiJauhari

tarushi_components

2020-10-02 09:57 UTC, dsquare0601 requested changes
**About_College :** 
1. Edit Button Not Appearing, So Can't Edit Details.
2. After Adding Details, It's Not Showing On View Page.

**NSS/Student Section**
1. File Control's Internal Label (Choose File) - Not Showing or Shows 'Change File' On Page Start instead of 'Choose File'

**Common**
1. Add 'accept' attribute in the file upload control for specific extensions.

2020-10-02 15:43 UTC, Jagruti245 requested changes
1. Women Cell :

2020-10-03 06:24 UTC, dsquare0601 approved these changes

2020-10-03 06:24 UTC, Jagruti245 approved these changes

2020-10-03 06:26 UTC, merged